#!/bin/bash
build() {
    add_binary /bin/bash
    add_binary /usr/bin/[
    add_binary /usr/bin/sha512sum
    add_binary /usr/bin/awk
    add_binary /usr/bin/ykchalresp
    add_binary /usr/bin/ykinfo
    add_binary /usr/bin/expect
    add_binary /usr/bin/cryptsetup
    add_binary /usr/bin/cat
    add_binary /usr/bin/tr
    add_binary /usr/bin/getopt
    add_binary /usr/bin/blkid
    add_binary /usr/bin/ykchrde.sh

    add_file /etc/ykchrde.conf

    add_full_dir /usr/lib/tcl8.6

    add_runscript

}

help() {
    cat <<HELPEOF
    This hook adds support to unlock luks containers encrypted with ykchrde at boot time while using systemd initramfs
HELPEOF
}
